name: flutter_app
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  english_words: ^3.1.0
  http: ^0.12.0
  cached_network_image: ^1.1.1
  json_annotation: ^2.0.0

  dio: 2.1.13

  flutter_swiper : ^1.1.6
  flutter_webview_plugin: ^0.3.5

  image_picker: ^0.6.1





dev_dependencies:
  flutter_test:
    sdk: flutter




  #这两个是dev的，不要放到上面去了哦
  build_runner: ^1.0.0
  json_serializable: ^2.0.0


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  assets:
    - images/res_icon_201.png
    - images/res_icon_202.png
    - images/res_icon_203.png
    - images/res_icon_204.png
    - images/res_icon_236.png
    - images/res_icon_237.png
    - images/res_icon_238.png
    - images/res_icon_239.png
    - images/res_icon_307.png
    - images/res_icon_306.png
    - images/res_icon_213.png
    - images/res_icon_130.png
    - images/res_icon_131.png
    - images/res_icon_132.png
    - images/res_icon_133.png
    - images/res_icon_246.png
    - images/res_icon_311.png
    - images/res_icon_225.png
    - images/res_icon_228.png

    - images/res_icon_101.png
    - images/res_icon_102.png
    - images/res_icon_103.png
    - images/res_icon_104.png
    - images/res_icon_105.png
    - images/res_icon_205.png
    - images/res_icon_206.png

    - images/res_icon_catagory_bg.png
    - images/lake.jpg
    - images/my_bg.png
    - web/html/bookDetails.html
